//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoviesLibrary.Web.MoviesLibraryService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Movie", Namespace="http://schemas.datacontract.org/2004/07/MoviesLibrary.Service.DataContracts")]
    [System.SerializableAttribute()]
    public partial class Movie : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<string> CastField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClassificationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GenreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MovieIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RatingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ReleaseDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<string> Cast {
            get {
                return this.CastField;
            }
            set {
                if ((object.ReferenceEquals(this.CastField, value) != true)) {
                    this.CastField = value;
                    this.RaisePropertyChanged("Cast");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Classification {
            get {
                return this.ClassificationField;
            }
            set {
                if ((object.ReferenceEquals(this.ClassificationField, value) != true)) {
                    this.ClassificationField = value;
                    this.RaisePropertyChanged("Classification");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Genre {
            get {
                return this.GenreField;
            }
            set {
                if ((object.ReferenceEquals(this.GenreField, value) != true)) {
                    this.GenreField = value;
                    this.RaisePropertyChanged("Genre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MovieId {
            get {
                return this.MovieIdField;
            }
            set {
                if ((this.MovieIdField.Equals(value) != true)) {
                    this.MovieIdField = value;
                    this.RaisePropertyChanged("MovieId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Rating {
            get {
                return this.RatingField;
            }
            set {
                if ((this.RatingField.Equals(value) != true)) {
                    this.RatingField = value;
                    this.RaisePropertyChanged("Rating");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ReleaseDate {
            get {
                return this.ReleaseDateField;
            }
            set {
                if ((this.ReleaseDateField.Equals(value) != true)) {
                    this.ReleaseDateField = value;
                    this.RaisePropertyChanged("ReleaseDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MoviesLibraryService.IMoviesLibraryService")]
    public interface IMoviesLibraryService {
        
        // CODEGEN: Generating message contract since the operation GetAllMovies is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMoviesLibraryService/GetAllMovies", ReplyAction="http://tempuri.org/IMoviesLibraryService/GetAllMoviesResponse")]
        MoviesLibrary.Web.MoviesLibraryService.GetAllMoviesResponse GetAllMovies(MoviesLibrary.Web.MoviesLibraryService.GetAllMoviesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IMoviesLibraryService/GetAllMovies", ReplyAction="http://tempuri.org/IMoviesLibraryService/GetAllMoviesResponse")]
        System.IAsyncResult BeginGetAllMovies(MoviesLibrary.Web.MoviesLibraryService.GetAllMoviesRequest request, System.AsyncCallback callback, object asyncState);
        
        MoviesLibrary.Web.MoviesLibraryService.GetAllMoviesResponse EndGetAllMovies(System.IAsyncResult result);
        
        // CODEGEN: Generating message contract since the wrapper name (GetMovieByIdRequest) of message GetMovieByIdRequest does not match the default value (GetMovieById)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMoviesLibraryService/GetMovieById", ReplyAction="http://tempuri.org/IMoviesLibraryService/GetMovieByIdResponse")]
        MoviesLibrary.Web.MoviesLibraryService.GetMovieByIdResponse GetMovieById(MoviesLibrary.Web.MoviesLibraryService.GetMovieByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IMoviesLibraryService/GetMovieById", ReplyAction="http://tempuri.org/IMoviesLibraryService/GetMovieByIdResponse")]
        System.IAsyncResult BeginGetMovieById(MoviesLibrary.Web.MoviesLibraryService.GetMovieByIdRequest request, System.AsyncCallback callback, object asyncState);
        
        MoviesLibrary.Web.MoviesLibraryService.GetMovieByIdResponse EndGetMovieById(System.IAsyncResult result);
        
        // CODEGEN: Generating message contract since the wrapper name (UpdateMovieRequest) of message UpdateMovieRequest does not match the default value (UpdateMovie)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMoviesLibraryService/UpdateMovie", ReplyAction="http://tempuri.org/IMoviesLibraryService/UpdateMovieResponse")]
        MoviesLibrary.Web.MoviesLibraryService.UpdateMovieResponse UpdateMovie(MoviesLibrary.Web.MoviesLibraryService.UpdateMovieRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IMoviesLibraryService/UpdateMovie", ReplyAction="http://tempuri.org/IMoviesLibraryService/UpdateMovieResponse")]
        System.IAsyncResult BeginUpdateMovie(MoviesLibrary.Web.MoviesLibraryService.UpdateMovieRequest request, System.AsyncCallback callback, object asyncState);
        
        MoviesLibrary.Web.MoviesLibraryService.UpdateMovieResponse EndUpdateMovie(System.IAsyncResult result);
        
        // CODEGEN: Generating message contract since the wrapper name (CreateMovieRequest) of message CreateMovieRequest does not match the default value (CreateMovie)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMoviesLibraryService/CreateMovie", ReplyAction="http://tempuri.org/IMoviesLibraryService/CreateMovieResponse")]
        MoviesLibrary.Web.MoviesLibraryService.CreateMovieResponse CreateMovie(MoviesLibrary.Web.MoviesLibraryService.CreateMovieRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IMoviesLibraryService/CreateMovie", ReplyAction="http://tempuri.org/IMoviesLibraryService/CreateMovieResponse")]
        System.IAsyncResult BeginCreateMovie(MoviesLibrary.Web.MoviesLibraryService.CreateMovieRequest request, System.AsyncCallback callback, object asyncState);
        
        MoviesLibrary.Web.MoviesLibraryService.CreateMovieResponse EndCreateMovie(System.IAsyncResult result);
        
        // CODEGEN: Generating message contract since the wrapper name (SearchMoviesRequest) of message SearchMoviesRequest does not match the default value (SearchMovies)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMoviesLibraryService/SearchMovies", ReplyAction="http://tempuri.org/IMoviesLibraryService/SearchMoviesResponse")]
        MoviesLibrary.Web.MoviesLibraryService.GetAllMoviesResponse SearchMovies(MoviesLibrary.Web.MoviesLibraryService.SearchMoviesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IMoviesLibraryService/SearchMovies", ReplyAction="http://tempuri.org/IMoviesLibraryService/SearchMoviesResponse")]
        System.IAsyncResult BeginSearchMovies(MoviesLibrary.Web.MoviesLibraryService.SearchMoviesRequest request, System.AsyncCallback callback, object asyncState);
        
        MoviesLibrary.Web.MoviesLibraryService.GetAllMoviesResponse EndSearchMovies(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllMoviesRequest {
        
        public GetAllMoviesRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAllMoviesResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAllMoviesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<MoviesLibrary.Web.MoviesLibraryService.Movie> Movies;
        
        public GetAllMoviesResponse() {
        }
        
        public GetAllMoviesResponse(System.Collections.Generic.List<MoviesLibrary.Web.MoviesLibraryService.Movie> Movies) {
            this.Movies = Movies;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMovieByIdRequest", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetMovieByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int MovieId;
        
        public GetMovieByIdRequest() {
        }
        
        public GetMovieByIdRequest(int MovieId) {
            this.MovieId = MovieId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMovieByIdResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetMovieByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public MoviesLibrary.Web.MoviesLibraryService.Movie Movie;
        
        public GetMovieByIdResponse() {
        }
        
        public GetMovieByIdResponse(MoviesLibrary.Web.MoviesLibraryService.Movie Movie) {
            this.Movie = Movie;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateMovieRequest", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateMovieRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public MoviesLibrary.Web.MoviesLibraryService.Movie Movie;
        
        public UpdateMovieRequest() {
        }
        
        public UpdateMovieRequest(MoviesLibrary.Web.MoviesLibraryService.Movie Movie) {
            this.Movie = Movie;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateMovieResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateMovieResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int MovieId;
        
        public UpdateMovieResponse() {
        }
        
        public UpdateMovieResponse(int MovieId) {
            this.MovieId = MovieId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateMovieRequest", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CreateMovieRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public MoviesLibrary.Web.MoviesLibraryService.Movie Movie;
        
        public CreateMovieRequest() {
        }
        
        public CreateMovieRequest(MoviesLibrary.Web.MoviesLibraryService.Movie Movie) {
            this.Movie = Movie;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateMovieResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CreateMovieResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int MovieId;
        
        public CreateMovieResponse() {
        }
        
        public CreateMovieResponse(int MovieId) {
            this.MovieId = MovieId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchMoviesRequest", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SearchMoviesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string SearchText;
        
        public SearchMoviesRequest() {
        }
        
        public SearchMoviesRequest(string SearchText) {
            this.SearchText = SearchText;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMoviesLibraryServiceChannel : MoviesLibrary.Web.MoviesLibraryService.IMoviesLibraryService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetAllMoviesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetAllMoviesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.Generic.List<MoviesLibrary.Web.MoviesLibraryService.Movie> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.Generic.List<MoviesLibrary.Web.MoviesLibraryService.Movie>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetMovieByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetMovieByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public MoviesLibrary.Web.MoviesLibraryService.Movie Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((MoviesLibrary.Web.MoviesLibraryService.Movie)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UpdateMovieCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public UpdateMovieCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CreateMovieCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public CreateMovieCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SearchMoviesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SearchMoviesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.Generic.List<MoviesLibrary.Web.MoviesLibraryService.Movie> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.Generic.List<MoviesLibrary.Web.MoviesLibraryService.Movie>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MoviesLibraryServiceClient : System.ServiceModel.ClientBase<MoviesLibrary.Web.MoviesLibraryService.IMoviesLibraryService>, MoviesLibrary.Web.MoviesLibraryService.IMoviesLibraryService {
        
        private BeginOperationDelegate onBeginGetAllMoviesDelegate;
        
        private EndOperationDelegate onEndGetAllMoviesDelegate;
        
        private System.Threading.SendOrPostCallback onGetAllMoviesCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetMovieByIdDelegate;
        
        private EndOperationDelegate onEndGetMovieByIdDelegate;
        
        private System.Threading.SendOrPostCallback onGetMovieByIdCompletedDelegate;
        
        private BeginOperationDelegate onBeginUpdateMovieDelegate;
        
        private EndOperationDelegate onEndUpdateMovieDelegate;
        
        private System.Threading.SendOrPostCallback onUpdateMovieCompletedDelegate;
        
        private BeginOperationDelegate onBeginCreateMovieDelegate;
        
        private EndOperationDelegate onEndCreateMovieDelegate;
        
        private System.Threading.SendOrPostCallback onCreateMovieCompletedDelegate;
        
        private BeginOperationDelegate onBeginSearchMoviesDelegate;
        
        private EndOperationDelegate onEndSearchMoviesDelegate;
        
        private System.Threading.SendOrPostCallback onSearchMoviesCompletedDelegate;
        
        public MoviesLibraryServiceClient() {
        }
        
        public MoviesLibraryServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MoviesLibraryServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MoviesLibraryServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MoviesLibraryServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<GetAllMoviesCompletedEventArgs> GetAllMoviesCompleted;
        
        public event System.EventHandler<GetMovieByIdCompletedEventArgs> GetMovieByIdCompleted;
        
        public event System.EventHandler<UpdateMovieCompletedEventArgs> UpdateMovieCompleted;
        
        public event System.EventHandler<CreateMovieCompletedEventArgs> CreateMovieCompleted;
        
        public event System.EventHandler<SearchMoviesCompletedEventArgs> SearchMoviesCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MoviesLibrary.Web.MoviesLibraryService.GetAllMoviesResponse MoviesLibrary.Web.MoviesLibraryService.IMoviesLibraryService.GetAllMovies(MoviesLibrary.Web.MoviesLibraryService.GetAllMoviesRequest request) {
            return base.Channel.GetAllMovies(request);
        }
        
        public System.Collections.Generic.List<MoviesLibrary.Web.MoviesLibraryService.Movie> GetAllMovies() {
            MoviesLibrary.Web.MoviesLibraryService.GetAllMoviesRequest inValue = new MoviesLibrary.Web.MoviesLibraryService.GetAllMoviesRequest();
            MoviesLibrary.Web.MoviesLibraryService.GetAllMoviesResponse retVal = ((MoviesLibrary.Web.MoviesLibraryService.IMoviesLibraryService)(this)).GetAllMovies(inValue);
            return retVal.Movies;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult MoviesLibrary.Web.MoviesLibraryService.IMoviesLibraryService.BeginGetAllMovies(MoviesLibrary.Web.MoviesLibraryService.GetAllMoviesRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetAllMovies(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetAllMovies(System.AsyncCallback callback, object asyncState) {
            MoviesLibrary.Web.MoviesLibraryService.GetAllMoviesRequest inValue = new MoviesLibrary.Web.MoviesLibraryService.GetAllMoviesRequest();
            return ((MoviesLibrary.Web.MoviesLibraryService.IMoviesLibraryService)(this)).BeginGetAllMovies(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MoviesLibrary.Web.MoviesLibraryService.GetAllMoviesResponse MoviesLibrary.Web.MoviesLibraryService.IMoviesLibraryService.EndGetAllMovies(System.IAsyncResult result) {
            return base.Channel.EndGetAllMovies(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.Collections.Generic.List<MoviesLibrary.Web.MoviesLibraryService.Movie> EndGetAllMovies(System.IAsyncResult result) {
            MoviesLibrary.Web.MoviesLibraryService.GetAllMoviesResponse retVal = ((MoviesLibrary.Web.MoviesLibraryService.IMoviesLibraryService)(this)).EndGetAllMovies(result);
            return retVal.Movies;
        }
        
        private System.IAsyncResult OnBeginGetAllMovies(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginGetAllMovies(callback, asyncState);
        }
        
        private object[] OnEndGetAllMovies(System.IAsyncResult result) {
            System.Collections.Generic.List<MoviesLibrary.Web.MoviesLibraryService.Movie> retVal = this.EndGetAllMovies(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetAllMoviesCompleted(object state) {
            if ((this.GetAllMoviesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetAllMoviesCompleted(this, new GetAllMoviesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetAllMoviesAsync() {
            this.GetAllMoviesAsync(null);
        }
        
        public void GetAllMoviesAsync(object userState) {
            if ((this.onBeginGetAllMoviesDelegate == null)) {
                this.onBeginGetAllMoviesDelegate = new BeginOperationDelegate(this.OnBeginGetAllMovies);
            }
            if ((this.onEndGetAllMoviesDelegate == null)) {
                this.onEndGetAllMoviesDelegate = new EndOperationDelegate(this.OnEndGetAllMovies);
            }
            if ((this.onGetAllMoviesCompletedDelegate == null)) {
                this.onGetAllMoviesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetAllMoviesCompleted);
            }
            base.InvokeAsync(this.onBeginGetAllMoviesDelegate, null, this.onEndGetAllMoviesDelegate, this.onGetAllMoviesCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MoviesLibrary.Web.MoviesLibraryService.GetMovieByIdResponse MoviesLibrary.Web.MoviesLibraryService.IMoviesLibraryService.GetMovieById(MoviesLibrary.Web.MoviesLibraryService.GetMovieByIdRequest request) {
            return base.Channel.GetMovieById(request);
        }
        
        public MoviesLibrary.Web.MoviesLibraryService.Movie GetMovieById(int MovieId) {
            MoviesLibrary.Web.MoviesLibraryService.GetMovieByIdRequest inValue = new MoviesLibrary.Web.MoviesLibraryService.GetMovieByIdRequest();
            inValue.MovieId = MovieId;
            MoviesLibrary.Web.MoviesLibraryService.GetMovieByIdResponse retVal = ((MoviesLibrary.Web.MoviesLibraryService.IMoviesLibraryService)(this)).GetMovieById(inValue);
            return retVal.Movie;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult MoviesLibrary.Web.MoviesLibraryService.IMoviesLibraryService.BeginGetMovieById(MoviesLibrary.Web.MoviesLibraryService.GetMovieByIdRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetMovieById(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetMovieById(int MovieId, System.AsyncCallback callback, object asyncState) {
            MoviesLibrary.Web.MoviesLibraryService.GetMovieByIdRequest inValue = new MoviesLibrary.Web.MoviesLibraryService.GetMovieByIdRequest();
            inValue.MovieId = MovieId;
            return ((MoviesLibrary.Web.MoviesLibraryService.IMoviesLibraryService)(this)).BeginGetMovieById(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MoviesLibrary.Web.MoviesLibraryService.GetMovieByIdResponse MoviesLibrary.Web.MoviesLibraryService.IMoviesLibraryService.EndGetMovieById(System.IAsyncResult result) {
            return base.Channel.EndGetMovieById(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public MoviesLibrary.Web.MoviesLibraryService.Movie EndGetMovieById(System.IAsyncResult result) {
            MoviesLibrary.Web.MoviesLibraryService.GetMovieByIdResponse retVal = ((MoviesLibrary.Web.MoviesLibraryService.IMoviesLibraryService)(this)).EndGetMovieById(result);
            return retVal.Movie;
        }
        
        private System.IAsyncResult OnBeginGetMovieById(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int MovieId = ((int)(inValues[0]));
            return this.BeginGetMovieById(MovieId, callback, asyncState);
        }
        
        private object[] OnEndGetMovieById(System.IAsyncResult result) {
            MoviesLibrary.Web.MoviesLibraryService.Movie retVal = this.EndGetMovieById(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetMovieByIdCompleted(object state) {
            if ((this.GetMovieByIdCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetMovieByIdCompleted(this, new GetMovieByIdCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetMovieByIdAsync(int MovieId) {
            this.GetMovieByIdAsync(MovieId, null);
        }
        
        public void GetMovieByIdAsync(int MovieId, object userState) {
            if ((this.onBeginGetMovieByIdDelegate == null)) {
                this.onBeginGetMovieByIdDelegate = new BeginOperationDelegate(this.OnBeginGetMovieById);
            }
            if ((this.onEndGetMovieByIdDelegate == null)) {
                this.onEndGetMovieByIdDelegate = new EndOperationDelegate(this.OnEndGetMovieById);
            }
            if ((this.onGetMovieByIdCompletedDelegate == null)) {
                this.onGetMovieByIdCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetMovieByIdCompleted);
            }
            base.InvokeAsync(this.onBeginGetMovieByIdDelegate, new object[] {
                        MovieId}, this.onEndGetMovieByIdDelegate, this.onGetMovieByIdCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MoviesLibrary.Web.MoviesLibraryService.UpdateMovieResponse MoviesLibrary.Web.MoviesLibraryService.IMoviesLibraryService.UpdateMovie(MoviesLibrary.Web.MoviesLibraryService.UpdateMovieRequest request) {
            return base.Channel.UpdateMovie(request);
        }
        
        public int UpdateMovie(MoviesLibrary.Web.MoviesLibraryService.Movie Movie) {
            MoviesLibrary.Web.MoviesLibraryService.UpdateMovieRequest inValue = new MoviesLibrary.Web.MoviesLibraryService.UpdateMovieRequest();
            inValue.Movie = Movie;
            MoviesLibrary.Web.MoviesLibraryService.UpdateMovieResponse retVal = ((MoviesLibrary.Web.MoviesLibraryService.IMoviesLibraryService)(this)).UpdateMovie(inValue);
            return retVal.MovieId;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult MoviesLibrary.Web.MoviesLibraryService.IMoviesLibraryService.BeginUpdateMovie(MoviesLibrary.Web.MoviesLibraryService.UpdateMovieRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginUpdateMovie(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginUpdateMovie(MoviesLibrary.Web.MoviesLibraryService.Movie Movie, System.AsyncCallback callback, object asyncState) {
            MoviesLibrary.Web.MoviesLibraryService.UpdateMovieRequest inValue = new MoviesLibrary.Web.MoviesLibraryService.UpdateMovieRequest();
            inValue.Movie = Movie;
            return ((MoviesLibrary.Web.MoviesLibraryService.IMoviesLibraryService)(this)).BeginUpdateMovie(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MoviesLibrary.Web.MoviesLibraryService.UpdateMovieResponse MoviesLibrary.Web.MoviesLibraryService.IMoviesLibraryService.EndUpdateMovie(System.IAsyncResult result) {
            return base.Channel.EndUpdateMovie(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public int EndUpdateMovie(System.IAsyncResult result) {
            MoviesLibrary.Web.MoviesLibraryService.UpdateMovieResponse retVal = ((MoviesLibrary.Web.MoviesLibraryService.IMoviesLibraryService)(this)).EndUpdateMovie(result);
            return retVal.MovieId;
        }
        
        private System.IAsyncResult OnBeginUpdateMovie(object[] inValues, System.AsyncCallback callback, object asyncState) {
            MoviesLibrary.Web.MoviesLibraryService.Movie Movie = ((MoviesLibrary.Web.MoviesLibraryService.Movie)(inValues[0]));
            return this.BeginUpdateMovie(Movie, callback, asyncState);
        }
        
        private object[] OnEndUpdateMovie(System.IAsyncResult result) {
            int retVal = this.EndUpdateMovie(result);
            return new object[] {
                    retVal};
        }
        
        private void OnUpdateMovieCompleted(object state) {
            if ((this.UpdateMovieCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.UpdateMovieCompleted(this, new UpdateMovieCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void UpdateMovieAsync(MoviesLibrary.Web.MoviesLibraryService.Movie Movie) {
            this.UpdateMovieAsync(Movie, null);
        }
        
        public void UpdateMovieAsync(MoviesLibrary.Web.MoviesLibraryService.Movie Movie, object userState) {
            if ((this.onBeginUpdateMovieDelegate == null)) {
                this.onBeginUpdateMovieDelegate = new BeginOperationDelegate(this.OnBeginUpdateMovie);
            }
            if ((this.onEndUpdateMovieDelegate == null)) {
                this.onEndUpdateMovieDelegate = new EndOperationDelegate(this.OnEndUpdateMovie);
            }
            if ((this.onUpdateMovieCompletedDelegate == null)) {
                this.onUpdateMovieCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnUpdateMovieCompleted);
            }
            base.InvokeAsync(this.onBeginUpdateMovieDelegate, new object[] {
                        Movie}, this.onEndUpdateMovieDelegate, this.onUpdateMovieCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MoviesLibrary.Web.MoviesLibraryService.CreateMovieResponse MoviesLibrary.Web.MoviesLibraryService.IMoviesLibraryService.CreateMovie(MoviesLibrary.Web.MoviesLibraryService.CreateMovieRequest request) {
            return base.Channel.CreateMovie(request);
        }
        
        public int CreateMovie(MoviesLibrary.Web.MoviesLibraryService.Movie Movie) {
            MoviesLibrary.Web.MoviesLibraryService.CreateMovieRequest inValue = new MoviesLibrary.Web.MoviesLibraryService.CreateMovieRequest();
            inValue.Movie = Movie;
            MoviesLibrary.Web.MoviesLibraryService.CreateMovieResponse retVal = ((MoviesLibrary.Web.MoviesLibraryService.IMoviesLibraryService)(this)).CreateMovie(inValue);
            return retVal.MovieId;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult MoviesLibrary.Web.MoviesLibraryService.IMoviesLibraryService.BeginCreateMovie(MoviesLibrary.Web.MoviesLibraryService.CreateMovieRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginCreateMovie(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginCreateMovie(MoviesLibrary.Web.MoviesLibraryService.Movie Movie, System.AsyncCallback callback, object asyncState) {
            MoviesLibrary.Web.MoviesLibraryService.CreateMovieRequest inValue = new MoviesLibrary.Web.MoviesLibraryService.CreateMovieRequest();
            inValue.Movie = Movie;
            return ((MoviesLibrary.Web.MoviesLibraryService.IMoviesLibraryService)(this)).BeginCreateMovie(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MoviesLibrary.Web.MoviesLibraryService.CreateMovieResponse MoviesLibrary.Web.MoviesLibraryService.IMoviesLibraryService.EndCreateMovie(System.IAsyncResult result) {
            return base.Channel.EndCreateMovie(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public int EndCreateMovie(System.IAsyncResult result) {
            MoviesLibrary.Web.MoviesLibraryService.CreateMovieResponse retVal = ((MoviesLibrary.Web.MoviesLibraryService.IMoviesLibraryService)(this)).EndCreateMovie(result);
            return retVal.MovieId;
        }
        
        private System.IAsyncResult OnBeginCreateMovie(object[] inValues, System.AsyncCallback callback, object asyncState) {
            MoviesLibrary.Web.MoviesLibraryService.Movie Movie = ((MoviesLibrary.Web.MoviesLibraryService.Movie)(inValues[0]));
            return this.BeginCreateMovie(Movie, callback, asyncState);
        }
        
        private object[] OnEndCreateMovie(System.IAsyncResult result) {
            int retVal = this.EndCreateMovie(result);
            return new object[] {
                    retVal};
        }
        
        private void OnCreateMovieCompleted(object state) {
            if ((this.CreateMovieCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CreateMovieCompleted(this, new CreateMovieCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CreateMovieAsync(MoviesLibrary.Web.MoviesLibraryService.Movie Movie) {
            this.CreateMovieAsync(Movie, null);
        }
        
        public void CreateMovieAsync(MoviesLibrary.Web.MoviesLibraryService.Movie Movie, object userState) {
            if ((this.onBeginCreateMovieDelegate == null)) {
                this.onBeginCreateMovieDelegate = new BeginOperationDelegate(this.OnBeginCreateMovie);
            }
            if ((this.onEndCreateMovieDelegate == null)) {
                this.onEndCreateMovieDelegate = new EndOperationDelegate(this.OnEndCreateMovie);
            }
            if ((this.onCreateMovieCompletedDelegate == null)) {
                this.onCreateMovieCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCreateMovieCompleted);
            }
            base.InvokeAsync(this.onBeginCreateMovieDelegate, new object[] {
                        Movie}, this.onEndCreateMovieDelegate, this.onCreateMovieCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MoviesLibrary.Web.MoviesLibraryService.GetAllMoviesResponse MoviesLibrary.Web.MoviesLibraryService.IMoviesLibraryService.SearchMovies(MoviesLibrary.Web.MoviesLibraryService.SearchMoviesRequest request) {
            return base.Channel.SearchMovies(request);
        }
        
        public System.Collections.Generic.List<MoviesLibrary.Web.MoviesLibraryService.Movie> SearchMovies(string SearchText) {
            MoviesLibrary.Web.MoviesLibraryService.SearchMoviesRequest inValue = new MoviesLibrary.Web.MoviesLibraryService.SearchMoviesRequest();
            inValue.SearchText = SearchText;
            MoviesLibrary.Web.MoviesLibraryService.GetAllMoviesResponse retVal = ((MoviesLibrary.Web.MoviesLibraryService.IMoviesLibraryService)(this)).SearchMovies(inValue);
            return retVal.Movies;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult MoviesLibrary.Web.MoviesLibraryService.IMoviesLibraryService.BeginSearchMovies(MoviesLibrary.Web.MoviesLibraryService.SearchMoviesRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSearchMovies(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginSearchMovies(string SearchText, System.AsyncCallback callback, object asyncState) {
            MoviesLibrary.Web.MoviesLibraryService.SearchMoviesRequest inValue = new MoviesLibrary.Web.MoviesLibraryService.SearchMoviesRequest();
            inValue.SearchText = SearchText;
            return ((MoviesLibrary.Web.MoviesLibraryService.IMoviesLibraryService)(this)).BeginSearchMovies(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MoviesLibrary.Web.MoviesLibraryService.GetAllMoviesResponse MoviesLibrary.Web.MoviesLibraryService.IMoviesLibraryService.EndSearchMovies(System.IAsyncResult result) {
            return base.Channel.EndSearchMovies(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.Collections.Generic.List<MoviesLibrary.Web.MoviesLibraryService.Movie> EndSearchMovies(System.IAsyncResult result) {
            MoviesLibrary.Web.MoviesLibraryService.GetAllMoviesResponse retVal = ((MoviesLibrary.Web.MoviesLibraryService.IMoviesLibraryService)(this)).EndSearchMovies(result);
            return retVal.Movies;
        }
        
        private System.IAsyncResult OnBeginSearchMovies(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string SearchText = ((string)(inValues[0]));
            return this.BeginSearchMovies(SearchText, callback, asyncState);
        }
        
        private object[] OnEndSearchMovies(System.IAsyncResult result) {
            System.Collections.Generic.List<MoviesLibrary.Web.MoviesLibraryService.Movie> retVal = this.EndSearchMovies(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSearchMoviesCompleted(object state) {
            if ((this.SearchMoviesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SearchMoviesCompleted(this, new SearchMoviesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SearchMoviesAsync(string SearchText) {
            this.SearchMoviesAsync(SearchText, null);
        }
        
        public void SearchMoviesAsync(string SearchText, object userState) {
            if ((this.onBeginSearchMoviesDelegate == null)) {
                this.onBeginSearchMoviesDelegate = new BeginOperationDelegate(this.OnBeginSearchMovies);
            }
            if ((this.onEndSearchMoviesDelegate == null)) {
                this.onEndSearchMoviesDelegate = new EndOperationDelegate(this.OnEndSearchMovies);
            }
            if ((this.onSearchMoviesCompletedDelegate == null)) {
                this.onSearchMoviesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSearchMoviesCompleted);
            }
            base.InvokeAsync(this.onBeginSearchMoviesDelegate, new object[] {
                        SearchText}, this.onEndSearchMoviesDelegate, this.onSearchMoviesCompletedDelegate, userState);
        }
    }
}
